### PR TITLE
updated jackson dependencies to 2.12.3

### PR DESCRIPTION
**Pull request by wallind**
Updates `com.fasterxml.jackson.core` dependencies to more recent version which accomplishes two things:

1. Makes this sdk compatible with SpringBoot version 2.5 (current known compatibility ends at 2.4.5) which uses `com.fasterxml.jackson.core` dependencies at 2.12.3 (see https://docs.spring.io/spring-boot/docs/2.5.0/reference/html/dependency-versions.html#dependency-versions). Prior to this update to the dependencies SpringBoot 2.5 will break when combined with this SDK and certain SpringBoot functionality usages. See example below:
```
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'boolean com.fasterxml.jackson.databind.SerializationConfig.hasExplicitTimeZone()'
```

2. Fixes a failing `maven clean package`

### CODE REVIEW

**Comment by jamesrowe08** [comment]
Ideally, jackson should be a transitive dependency. The issue is these are packaged into the uber jar.

**Comment by wallind** [comment]
> Ideally, jackson should be a transitive dependency. The issue is these are packaged into the uber jar.

@jamesrowe08 out of curiosity are you a maintainer/know-a-maintainer?

To be transparent I'm only 1 year into my Java experience so while I have a loose grasp on Maven/Gradle/dependency-management I'm really no expert so I don't really know exactly what you mean by:

> should be a transitive dependency

I only knew that this package was having an issue when we upgraded Spring as mentioned and that I was able to resolve the issue by bumping up these dependencies and manually building a jar and including it in our source control. A naive solution probably but a solution none-the-less.

If you could explain a bit more context or offer some reference links I might be interested in adjusting this PR or making a new one....however if you're not a maintainer or don't know them I may not because obviously this PR has received very little attention over the past year.

**Comment by jamesrowe08** [comment]
I’m not a maintainer, but had to do the same thing you did. Gradle/Maven when adding dependencies should recognize the transitive dependencies and if there are dependency conflict/collisions within your project then it will pick the appropriate version. 

With the way this jar is built, it doesn’t expose the dependencies to the build process. For instance, when you pull this dependency into your own project it has no idea that this is using Jackson. 

Look at your gradle or maven dependency tree when you pull this in. You’ll see other dependencies have trees of transitive dependencies, while this library declares none.

**Comment by jav** [comment]
Sorry about my inactivity.
@oliverwelter has offered to be a new maintainer.
The new repository lies here: https://github.com/nia-medtech/expo-server-sdk-java

**Pull request closed without merging**
