### PR TITLE
make ExpoMessageSound constructors public

### PR DESCRIPTION
**Pull request by tiepp**
Make it possible to declare sound properties by setting constructor visibility to public.

### CODE REVIEW

**Comment by jav** [comment]
FYI: In future versions, I intend to deprecate the multi arg constructors in favor of builder pattern.

**Comment by tiepp** [comment]
Using builders is a great idea. If you need any support, I'm happy to help.

For now, is it possible to release the changes from this PR soon? As currently a reflection hack is necessary to enable sound on iOS notifications.

**Comment by jav** [comment]
Done. 

Version 0.5.3 is released.

It should pop up in [mvnrepository.com](https://mvnrepository.com/artifact/io.github.jav/expo-server-sdk) and [search.maven.org](https://search.maven.org/artifact/io.github.jav/expo-server-sdk) any moment now.

**Comment by jav** [comment]
By the way. 
Thank you for pointing out the error and for the Pull Request ! :)

**Comment by tiepp** [comment]
That was amazingly fast! Thanks a lot!

**Pull request merged**
